### ISSUE TITLE
Add support for JIRA

### ISSUE THREAD

**Issue by slavafomin** [jurgenhaas/toggl-button-greasemonkey#21]
I would love to see support for JIRA ;)

Here's the link to [try JIRA for free](https://www.atlassian.com/software/jira/try/) in case someone decides to implement it.

**Comment by jurgenhaas** [comment]
Hi @slavafomin if you'Re still interested please move over to https://gitlab.paragon-es.de/groups/toggl-button where this project lives from now on with a more granular structure.
