### ISSUE TITLE
authorElem for Github

### ISSUE THREAD

**Issue by sagikazarmark** [jurgenhaas/toggl-button-greasemonkey#35]
Is it a good idea to use the owner of the repository as the author element? What about organizations? Or am I missing some points here?

**Comment by jurgenhaas** [comment]
As far as I'm aware, the selector ".url.fn" is also used for organisations, isn't it?

**Comment by sagikazarmark** [comment]
Yeah, that's the problem. Shouldn't the authorElem refer to a person and not an organization?

**Comment by jurgenhaas** [comment]
That's not necessary. The authorElem is there to provide meta data about the current issue which will help to remember the associated project on Toggl. As long as the content in authorElem is the same, the Toggl button will now propose the same project for all issues in this GitHub project for that organisation.

**Comment by sagikazarmark** [comment]
I see. Thanks for clarifying.
